name: news_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  go_router: ^13.2.0
  http: ^1.2.1
  rive: ^0.12.4
  riverpod_annotation: ^2.3.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
      - family: Satoshi
        fonts:
          - asset: fonts/Satoshi-Black.otf
          - asset: fonts/Satoshi-BlackItalic.otf
            style: italic
          - asset: fonts/Satoshi-Bold.otf
          - asset: fonts/Satoshi-BoldItalic.otf
          - asset: fonts/Satoshi-Italic.otf
          - asset: fonts/Satoshi-Light.otf
          - asset: fonts/Satoshi-LightItalic.otf
          - asset: fonts/Satoshi-Medium.otf
          - asset: fonts/Satoshi-MediumItalic.otf
          - asset: fonts/Satoshi-Regular.otf