name: news_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  async: ^2.11.0
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_generative_ai: ^0.2.2
  html: ^0.15.4
  http: ^1.2.1
  rive: ^0.12.4
  riverpod_annotation: ^2.3.4
  share_plus: ^7.2.2
  text_to_speech: ^0.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/rive/

  fonts:
      - family: Satoshi
        fonts:
          - asset: fonts/Satoshi-Black.otf
          - asset: fonts/Satoshi-BlackItalic.otf
            style: italic
          - asset: fonts/Satoshi-Bold.otf
          - asset: fonts/Satoshi-BoldItalic.otf
          - asset: fonts/Satoshi-Italic.otf
          - asset: fonts/Satoshi-Light.otf
          - asset: fonts/Satoshi-LightItalic.otf
          - asset: fonts/Satoshi-Medium.otf
          - asset: fonts/Satoshi-MediumItalic.otf
          - asset: fonts/Satoshi-Regular.otf



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo.jpg"
    background_color: "#984061"
    theme_color: "#984061"
  windows:
    generate: true
    image_path: "assets/images/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.jpg"


flutter_native_splash:
  color: "#984061"
  fullscreen: false
  android_gravity: fill
  ios_content_mode: scaleToFill
  web_image_mode: cover